### ISSUE TITLE
Ranking is not enough centered on Perl

### ISSUE THREAD

**Issue by dolmen** [metacpan/github-meets-cpan#2]
The "About" page says: « "Github Meets CPAN" presents a list of users who have set their Github account at MetaCPAN. »
So I expect that it ranks CPAN authors accordingly to some statistics related to **Perl** development on GitHub.

However it doesn't seem to be the case. General Github statistics are used instead of Perl related ones.
For example, [James Turnbull](http://www.github-meets-cpan.com/user/JAMTUR) is ranked #17 while he has only 1 CPAN module and 0 Perl projects on GitHub.

Here are some suggestion for tweaking the ranking formula:
- count only Perl projects (instead of all projects): Github repos for which the main language is Perl
  - watchers
  - forks
- count only followers that are interested in Perl: either have a CPAN ID or have themselves at least one repo whose main language is Perl
- do not count watchers who are also followers

**Comment by oalders** [comment]
Closing this as the outstanding issue to address is captured in #4
