### ISSUE TITLE
Updates stopped for months

### ISSUE THREAD

**Issue by creaktive** [metacpan/github-meets-cpan#20]
It says "Last Update: 2018-06-19T00:48:49" on the index page. Can I help somehow?

**Comment by oalders** [comment]
Thanks @creaktive. We should check our logs to see if the cron is running first.  If we need some help, we will be sure to ask.  :)

**Comment by trapd00r** [comment]
Interestingly, now it says:
`Last Update: 2018-11-10T20:19:53`

Does that mean that you ran a failing cron job manualy after this issue was created, and then forgot about it? ;)

**Comment by oalders** [comment]
That's probably exactly what happened. ;)  We're in the process of moving everything to Docker. If someone wants to set up a `Dockerfile` for this repo, that might speed up the process in getting things up and running again.

**Comment by oalders** [comment]
Actually, I'll set up the Docker stuff.  Would be a good warm-up for PTS.

**Comment by trapd00r** [comment]
Thank you @oalders. Docker is still just a buzzword for me (alas, I haven't grasped it yet)

**Comment by creaktive** [comment]
I’ll give it a try! Can you point me to a sample Dockerfile used at
anything MetaCPAN-related? Otherwise I use the example provided at
Mojolicious wiki.

**Comment by oalders** [comment]
@creaktive sounds good!  This is as far as I got:

```
$ cat docker-compose.yml
version: "3.4"
services:
  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - "27017:27017"
  web:
    image: perl:5.28.1
    depends_on:
      - mongodb
```

There is https://github.com/metacpan/metacpan-docker and https://github.com/metacpan/metacpan-web/blob/master/Dockerfile to get you started. :)

**Comment by oalders** [comment]
> Thank you @oalders. Docker is still just a buzzword for me (alas, I haven't grasped it yet)

@trapd00r I know how you feel.  I'm currently in the process of wrapping my head around this stuff. :)

**Comment by oalders** [comment]
@creaktive how is this coming along?

**Comment by oalders** [comment]
@creaktive I'm going to finish off the Docker stuff.

**Comment by creaktive** [comment]
Oh hai! Sorry, I've overestimated my Docker knowledge. Turns out I know nothing about composing <o>
I'll be looking forward learning from how you solved it :)
